import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { AtlasPage } from "./atlas-page";

vi.mock("../../common/markdown", () => ({
  Markdown: ({ children }: { children: string }) => <div data-testid="markdown-preview">{children}</div>,
}));

describe("AtlasPage workspace browser", () => {
  it("shows the workspace generated by the Atlas collection", () => {
    render(<AtlasPage />);

    expect(screen.getByRole("heading", { name: "AI Agent 学习资料包" })).toBeInTheDocument();
    expect(screen.getByText("AI Agent 项目调研")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "mission.md" })).toHaveAttribute("aria-pressed", "true");
    expect(screen.getByTestId("markdown-preview")).toHaveTextContent("## Agent 工作目标");
  });

  it("switches workspace files while keeping resource evidence visible", () => {
    render(<AtlasPage />);

    fireEvent.click(screen.getByRole("button", { name: "outputs/项目对比表.md" }));

    expect(screen.getByTestId("markdown-preview")).toHaveTextContent("# 项目对比表");
    expect(screen.getByText("browser-use 项目")).toBeInTheDocument();
    expect(screen.getByText(/仓库标题和 README/)).toBeInTheDocument();
    expect(screen.getByText(/哪些资源适合入门/)).toBeInTheDocument();
  });
});
